import { useEffect, useState } from "react";
import { site } from "@/content/site.config";
import { RunsIcon } from "./primitives";

export function Footer({
  cursorOn,
  onToggleCursor,
}: {
  cursorOn: boolean;
  onToggleCursor: () => void;
}) {
  const [email, setEmail] = useState("");

  // Assembled at runtime so the address is absent from view-source.
  useEffect(() => {
    setEmail(`${site.contact.user}${String.fromCharCode(64)}${site.contact.domain}`);
  }, []);

  return (
    <footer className="surface-indigo border-t-2 border-purple px-[clamp(20px,5vw,64px)] py-12">
      <div className="mx-auto grid max-w-[1320px] grid-cols-1 items-start gap-10 md:grid-cols-3 md:gap-12">
        <div className="order-2 md:order-1">
          <div className="flex items-center gap-2">
            <span aria-hidden="true" className="grid h-7 w-7 place-items-center rounded-md bg-gold font-display text-ink">
              C
            </span>
            <span className="font-display text-[20px] text-cream">Champhunt</span>
          </div>
          <p className="cream-muted mt-3 text-[13px]">Powered by Champhunt AI · In partnership with Willow TV</p>
          <p className="cream-muted mt-3 max-w-[42ch] text-[12px]">
            Rankings are generated by an automated model and reviewed before publication. Updated Mondays, 9am ET.
          </p>
          <button
            type="button"
            onClick={onToggleCursor}
            className="t-micro mt-4 inline-flex items-center gap-2 rounded-lg border-2 border-cream/30 px-3 py-2 text-cream hover:border-gold"
          >
            <span aria-hidden="true">↺</span>
            {cursorOn ? "Default cursor" : "Ball cursor"}
          </button>
        </div>

        <nav className="order-3 flex flex-col gap-2 md:order-2" aria-label="Footer">
          {[
            { label: "Rankings", href: "#rankings" },
            { label: "How it works", href: "#how-it-works" },
            { label: "Deals", href: "#deals" },
            { label: "Privacy", href: "/methodology" },
            { label: "Terms", href: "/methodology" },
          ].map((l) => (
            <a key={l.label} href={l.href} className="text-[14px] font-semibold text-cream hover:text-gold">
              {l.label}
            </a>
          ))}
        </nav>

        <div className="order-1 md:order-3">
          <h3 className="font-display text-[20px] text-cream">Contact us</h3>
          <p className="cream-muted mt-2 text-[13px]">Questions about the maths, or a partnership?</p>
          <a href={email ? `mailto:${email}` : undefined} className="mt-2 inline-block text-[14px] font-semibold text-gold underline">
            {email || "Loading address"}
          </a>
          <p className="cream-muted mt-6 flex items-center gap-2 text-[12px]">
            <RunsIcon size={14} />
            Runs have no cash value.
          </p>
          <p className="cream-muted mt-2 text-[12px]">© 2026 Champhunt Inc.</p>
        </div>
      </div>
    </footer>
  );
}
